{% set name = "apav" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/APAV-{{ version }}.tar.gz
  sha256: ae26caf1908da04ab88cfa6f16532ad8cb09548c2c11de40d95703afbc4f45d6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - poetry
    - cython
  run:
    - fast-histogram
    - lmfit >=1.0
    - numba
    - numpy >=1.17
    - periodictable
    - pyqt >=5.11
    - pyqtgraph >=0.11.0
    - pytest >=5
    - pytest-qt >=3
    - python
    - tabulate

test:
  imports:
    - apav
    - apav.analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/jesseds/apav
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'APAV: Python analysis for atom probe tomography'
  description: |
    APAV (Atom Probe Analysis and Visualization) is a Python library 
    for the analysis and visualization of atom probe tomography 
    experiments
  doc_url: https://apav.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/jesseds/apav

extra:
  recipe-maintainers:
    - jan-janssen
